spring:
  data:
    mongodb:
      username: localbusiness
      password: localbusiness
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  application:
    config:
      customer-url: http://localhost:8090
server:
  port: 8090
