spring:
  data:
    mongodb:
      username: tuser
      password: ms2024
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  application:
    config:
      customer-url: http://localhost:8090
server:
  port: 8090
