spring:
  data:
    mongodb:
      username: localbusiness
      password: localbusiness
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.localbusiness.ecommerce.kafka.OrderConfirmation,paymentConfirmation:com.localbusiness.ecommerce.notification.PaymentNotificationRequest
        spring.json.trusted.packages: '*'
  mail:
    host: localhost
    port: 1025
    username: localbusiness
    password: localbusiness
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 8040